version: '3.8'

services:
  liturgy-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: messe-app
    ports:
      - "7655:7655"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    networks:
      - liturgy-network

networks:
  liturgy-network:
    driver: bridge