# Version supprimée pour compatibilité avec Docker Compose v2

services:
  liturgy-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: messe-app
    ports:
      - "3000:80"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    networks:
      - liturgy-network


networks:
  liturgy-network:
    driver: bridge

volumes:
  nginx-logs:
    driver: local